import { readdir, writeFile } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'
import sharp from 'sharp'

const PUBLIC_DIR = join(process.cwd(), 'public')
const OUT_FILE = join(process.cwd(), 'lib', 'blur-data.ts')

// Landing hero carousel images are intentionally excluded from blur-up.
const EXCLUDE_PREFIXES = ['hero-carousel', 'hero-landing', 'hero-mobile']
const RASTER = /\.(jpe?g|png|webp|avif)$/i

async function walk(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full)))
    else if (RASTER.test(entry.name)) out.push(full)
  }
  return out
}

const files = (await walk(PUBLIC_DIR)).filter(
  (f) => !EXCLUDE_PREFIXES.some((p) => f.split(sep).pop().startsWith(p)),
)

const entries = {}
for (const file of files) {
  // Public path with leading slash + forward slashes (e.g. /events/contra.jpg)
  const publicPath = '/' + relative(PUBLIC_DIR, file).split(sep).join('/')
  try {
    const img = sharp(file)
    const meta = await img.metadata()
    const buf = await img
      .resize(20, 20, { fit: 'inside' })
      .jpeg({ quality: 40 })
      .toBuffer()
    entries[publicPath] = {
      blurDataURL: `data:image/jpeg;base64,${buf.toString('base64')}`,
      width: meta.width ?? 1200,
      height: meta.height ?? 1600,
    }
  } catch (err) {
    console.warn(`Skipped ${publicPath}: ${err.message}`)
  }
}

const body =
  `// AUTO-GENERATED by scripts/gen-blur.mjs — do not edit by hand.\n` +
  `// Tiny base64 LQIP previews + intrinsic dimensions keyed by public path,\n` +
  `// used for next/image blur placeholders.\n` +
  `export type BlurMeta = { blurDataURL: string; width: number; height: number }\n` +
  `export const blurDataMap: Record<string, BlurMeta> = ${JSON.stringify(entries, null, 2)}\n`

await writeFile(OUT_FILE, body)
console.log(`Wrote ${Object.keys(entries).length} blur placeholders to lib/blur-data.ts`)
